### ISSUE TITLE
Recognition failure for 2-characters manufacture brands

### ISSUE THREAD

**Issue by huangkaichang** [adaptant-labs/vin-decoder-dart#7]
Hi. Thanks for the package

I noticed the "wmi" is the first 3 characters of the vin number after normalization. 
```
VIN({required this.number, this.extended = false})
      : wmi = normalize(number).substring(0, 3),
        vds = normalize(number).substring(3, 9),
        vis = normalize(number).substring(9, 17);
```

But some of the brands' wmi is 2-characters, like Nissan(1N), in manufacturers map. 
`
'1N': 'Nissan',
`

So the getManufacturer() function will return "Unknown"
```
String? getManufacturer() {
    if (manufacturers.containsKey(this.wmi)) {
      return manufacturers[this.wmi];
    } else {
      return "Unknown (WMI: ${this.wmi.toUpperCase()})";
    }
  }
```

**Comment by pmundt** [comment]
Good catch, do you have an example VIN with a 2-character WMI I can add a unit test for? The VIN must still be 17 characters long, so I want to make sure I've accounted for the padding byte in the right place.

**Comment by pmundt** [comment]
Ok, I found an example from Toyota. In this case, the WMI doesn't change from 3 characters, it's just that the manufacturer ID is encoded in the first 2 characters and the 3rd is used to encode the vehicle type. I've added a fallback now so that if the full 3-char lookup fails, we try again with the 2nd. I'll include this in a 0.2.1 release to be pushed out soon. Thanks again for the report!
